CREATE TABLE IF NOT EXISTS bugs (
  id BIGINT NOT NULL AUTO_INCREMENT,
  bug_title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  severity VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

